### ISSUE TITLE
Marauder Weapons not patched

### ISSUE THREAD

**Issue by Whyareuhere** [N7Huntsman/Rimsenal-CombatExtended#1]
Weapons such as the Trench Carbine and the Contender for Marauders are not patched and thus cannot be used or fired by pawns. They show up with default Rimworld stats, so no ammo type, aiming sway stats, etc. Unsure about other guns patched, may need looking into.

Interestingly, the Varmit Rifle is already patched.

**Comment by N7Huntsman** [comment]
Rimsenal - Marauder isn't on Steam, as I recall, right? I'm happy to include it in the patch, but you'll have to send me a link to someplace I can download the mod.

**Comment by Whyareuhere** [comment]
https://ludeon.com/forums/index.php?topic=11160.0

This is the main Ludeon forum page for the Rimsenal mod. 

https://www.dropbox.com/sh/fksj8i446o3szi1/AAA6osi1ZSee_Kw0a3_yLvfma?dl=0

This Dropbox link is from that page, there is a Rimsenal Maurader mod in a .zip file.

**Comment by N7Huntsman** [comment]
Reopened for tracking purposes.

**Comment by N7Huntsman** [comment]
Patch for Rimsenal Marauders added, 2/16.
