### ISSUE TITLE
Federation weapons need conversion

### ISSUE THREAD

**Issue by Scynix** [N7Huntsman/Rimsenal-CombatExtended#6]
"Auxiliary Pistol" from the Rimsenal: Federation mod is missing CE ammo requirement.

**Comment by Scynix** [comment]
I apologize, I feel dumb for opening this now. As I've looked into this patch mod, I noticed you've done the Marauder and Security stuff, but the Federation hasn't been converted over yet. They lack the variable specifics the others have.

**Comment by N7Huntsman** [comment]
It is intentional that the federation weapons don't use ammo, though they generally deal poor damage. It makes sense with the lore, as their faction is stated to be isolated portions of a highly advanced, but failing galactic state.
